using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Text.RegularExpressions;
using NUnit.Framework;

namespace Lennox.LibYuvSharp.Tests
{
    [TestFixture]
    public class CodeGeneration
    {
        private static readonly string[] Headers = {
            "compare", "convert", "convert_argb", "convert_from", "convert_from_argb",
            "cpu_id", "planar_functions", "rotate", "rotate_argb", "scale",
            "scale_argb", "scale_rgb", "scale_uv", "video_common", "row"
        };

        private static readonly Dictionary<string, string> Types = new Dictionary<string, string>
        {
            { "uint8_t", "byte" }, { "int8_t", "sbyte" },
            { "uint16_t", "ushort" }, { "int16_t", "short" },
            { "uint32_t", "uint" }, { "int32_t", "int" },
            { "uint64_t", "ulong" }, { "int64_t", "long" },
            { "size_t", "UIntPtr" }, { "unsigned long", "uint" }, { "char", "sbyte" },
            { "void", "void" }, { "int", "int" }, { "float", "float" }, { "double", "double" },
            { "FilterMode", "FilterMode" }, { "RotationMode", "RotationMode" },
            // SIMD constant structures are opaque and their layout is platform specific.
            { "YuvConstants", "void" }, { "ArgbConstants", "void" }
        };

        private static string ManagedType(string nativeType)
        {
            nativeType = Regex.Replace(nativeType, @"\b(const|struct|enum)\s+", "").Trim();
            var pointers = nativeType.Count(c => c == '*');
            return Types[nativeType.Replace("*", "").Trim()] + new string('*', pointers);
        }

        /// <summary>
        /// Regenerates LibYuv.cs from LIBYUV_SOURCE (default: artifacts/libyuv).
        /// Only public functions exported by the packaged Windows x64 DLL are emitted.
        /// Run explicitly after building the pinned native source with build-libyuv.bat.
        /// </summary>
        [Test, Explicit]
        public void GenerateClassDefinition()
        {
            var root = new DirectoryInfo(TestContext.CurrentContext.TestDirectory);
            while (root != null && !File.Exists(Path.Combine(root.FullName, "LibYuvSharp.sln")))
                root = root.Parent;
            Assert.That(root, Is.Not.Null, "Cannot locate repository root.");
            var source = Environment.GetEnvironmentVariable("LIBYUV_SOURCE")
                ?? Path.Combine(root.FullName, "artifacts", "libyuv");
            var target = Path.Combine(root.FullName, "LibYuvSharp", "LibYuv.cs");
            var original = File.ReadAllText(target).Replace("\r\n", "\n").Replace("\n", "\r\n");
            var bodyStart = original.IndexOf("        //", original.IndexOf("private const string _path", StringComparison.Ordinal), StringComparison.Ordinal);
            var output = new StringBuilder(original.Substring(0, bodyStart));
            output.Append("        // Generated by LibYuvSharp.Test/CodeGeneration.cs from libyuv 1971.").Append("\r\n");
            output.Append("        // Upstream commit: af1aaca84027a69ab25f251ade1bf1714b180d89").Append("\r\n");
            output.Append("\r\n");
            var version = File.ReadAllText(Path.Combine(source, "include", "libyuv", "version.h"));
            Assert.That(version, Does.Contain("#define LIBYUV_VERSION 1971"));
            var dll = NativeLibrary.Load(Path.Combine(root.FullName, "LibYuvSharp", "lib", "runtimes", "win-x64", "native", "libyuv_internal.dll"));
            var names = new HashSet<string>();
            try
            {
                foreach (var header in Headers)
                {
                    var text = File.ReadAllText(Path.Combine(source, "include", "libyuv", header + ".h"));
                    // Keep adjacent API documentation, but strip comments within signatures.
                    var pattern = @"(?<comments>(?:(?://[^\r\n]*\r?\n)|\s)*)LIBYUV_API\s+(?<result>[\w\s*]+?)\s+(?<name>\w+)\s*\((?<args>[^;{}]*?)\)\s*;";
                    foreach (Match match in Regex.Matches(text, pattern))
                    {
                        var name = match.Groups["name"].Value;
                        // Retain the two row functions exposed by the original wrapper.
                        if (header == "row" && name != "ARGBAffineRow_C" && name != "ARGBAffineRow_SSE2") continue;
                        if (!NativeLibrary.TryGetExport(dll, name, out _) || !names.Add(name)) continue;
                        var args = new List<string>();
                        var parameters = Regex.Replace(match.Groups["args"].Value, @"//[^\n]*|/\*.*?\*/", "", RegexOptions.Singleline);
                        foreach (var parameter in parameters.Split(','))
                        {
                            var value = parameter.Trim();
                            if (value == "" || value == "void") continue;
                            var arg = Regex.Match(value, @"^(.+?[\s*])(\w+)(\[\d+\])?$");
                            Assert.That(arg.Success, Is.True, "Unsupported parameter: " + value);
                            var parameterName = arg.Groups[2].Value;
                            if (new[] { "base", "ref", "out", "in", "params", "event" }.Contains(parameterName))
                                parameterName = "@" + parameterName;
                            args.Add(ManagedType(arg.Groups[1].Value + (arg.Groups[3].Success ? "*" : "")) + " " + parameterName);
                        }
                        output.Append("        // include/libyuv/" + header + ".h").Append("\r\n");
                        var comments = match.Groups["comments"].Value.Trim();
                        if (comments.Length > 0)
                        {
                            output.Append("        /// <summary>").Append("\r\n");
                            foreach (var line in comments.Split('\n'))
                                output.Append(("        /// " + System.Security.SecurityElement.Escape(line.Trim().TrimStart('/').TrimStart())).TrimEnd()).Append("\r\n");
                            output.Append("        /// </summary>").Append("\r\n");
                        }
                        output.Append("        [DllImport(_path, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]").Append("\r\n");
                        output.Append("        public static extern " + ManagedType(match.Groups["result"].Value) + " " + name + "(");
                        output.Append(string.Join(",\r\n            ", args));
                        output.Append(");").Append("\r\n");
                        output.Append("\r\n");
                    }
                }
                // Preserve names for native APIs that were renamed without changing their ABI.
                var aliases = new Dictionary<string, string> {
                    { "NV21ToNV12", "NV12ToNV21" }, { "RotateUV90", "SplitRotateUV90" },
                    { "RotateUV180", "SplitRotateUV180" }, { "RotateUV270", "SplitRotateUV270" },
                    { "TransposeUV", "SplitTransposeUV" }
                };
                foreach (var alias in aliases)
                {
                    var declaration = Regex.Match(original, @"public static extern \w+ " + alias.Key + @"\([^;]+;");
                    Assert.That(declaration.Success, Is.True, "Missing compatibility declaration: " + alias.Key);
                    Assert.That(NativeLibrary.TryGetExport(dll, alias.Value, out _), Is.True);
                    output.Append("        /// <summary>Compatibility alias for " + alias.Value + ".</summary>").Append("\r\n");
                    output.Append("        [DllImport(_path, EntryPoint = \"" + alias.Value + "\", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]").Append("\r\n");
                    output.Append("        " + declaration.Value).Append("\r\n");
                    output.Append("\r\n");
                }
            }
            finally { NativeLibrary.Free(dll); }
            output.Append("    }").Append("\r\n");
            output.Append("}").Append("\r\n");
            File.WriteAllText(target, output.ToString(), new UTF8Encoding(false));
            TestContext.WriteLine("Generated " + names.Count + " public bindings and 5 compatibility aliases.");
        }
    }
}
