<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <RootNamespace>Lennox.LibYuvSharp.Tests</RootNamespace>
    <Platforms>AnyCPU;x64;ARM64</Platforms>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NativeRuntimeIdentifier Condition="'$(NativeRuntimeIdentifier)' == ''">$(NETCoreSdkRuntimeIdentifier)</NativeRuntimeIdentifier>
    <LibYuvPackageVersion Condition="'$(LibYuvPackageVersion)' == ''">2.0.0</LibYuvPackageVersion>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="solid-color.jpg" />
    <PackageReference Include="NUnit" Version="3.14.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
  </ItemGroup>
  <ItemGroup Condition="'$(UseNuGetPackage)' != 'true'">
    <ProjectReference Include="..\LibYuvSharp\LibYuvSharp.csproj" />
    <Content Include="..\LibYuvSharp\lib\runtimes\$(NativeRuntimeIdentifier)\native\*">
      <Link>%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup Condition="'$(UseNuGetPackage)' == 'true'">
    <PackageReference Include="Lennox.LibYuvSharp" Version="$(LibYuvPackageVersion)" />
  </ItemGroup>
</Project>
