# cmake -DRID=linux-x64 -P native/build.cmake
# Optional: TOOLCHAIN_FILE, CMAKE_C_COMPILER, CMAKE_CXX_COMPILER, ANDROID_NDK.
cmake_minimum_required(VERSION 3.16)
if(NOT RID MATCHES "^(win|linux|osx|android)-(x64|arm64)$")
  message(FATAL_ERROR "RID must be win/linux/osx/android-x64 or -arm64")
endif()
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
if(NOT LIBYUV_BUILD_ROOT)
  set(LIBYUV_BUILD_ROOT "${ROOT}/artifacts/native")
endif()
set(WORK "${LIBYUV_BUILD_ROOT}/${RID}")
set(SOURCE "${ROOT}/artifacts/libyuv")
set(REVISION af1aaca84027a69ab25f251ade1bf1714b180d89)
function(run)
  execute_process(COMMAND ${ARGV} RESULT_VARIABLE RESULT)
  if(NOT RESULT EQUAL 0)
    message(FATAL_ERROR "Command failed (${RESULT}): ${ARGV}")
  endif()
endfunction()
if(NOT EXISTS "${SOURCE}/.git")
  run(git clone --no-checkout --depth 1 https://chromium.googlesource.com/libyuv/libyuv "${SOURCE}")
endif()
run(git -C "${SOURCE}" fetch --depth 1 origin ${REVISION})
run(git -C "${SOURCE}" checkout --detach ${REVISION})
include("${CMAKE_CURRENT_LIST_DIR}/download-jpeg.cmake")

set(OPTIONS -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_POSITION_INDEPENDENT_CODE=ON
  -DCMAKE_C_STANDARD=99 -DCMAKE_CXX_STANDARD=11)
foreach(VAR CMAKE_C_COMPILER CMAKE_CXX_COMPILER)
  if(DEFINED ${VAR})
    list(APPEND OPTIONS "-D${VAR}=${${VAR}}")
  endif()
endforeach()
if(DEFINED TOOLCHAIN_FILE)
  list(APPEND OPTIONS "-DCMAKE_TOOLCHAIN_FILE=${TOOLCHAIN_FILE}")
endif()
if(RID MATCHES "^win-")
  if(NOT CMAKE_HOST_WIN32)
    message(FATAL_ERROR "Windows builds require a Windows host and an x64/ARM64 compiler")
  endif()
  if(RID STREQUAL "win-arm64")
    set(PROCESSOR ARM64)
  else()
    set(PROCESSOR AMD64)
  endif()
  list(APPEND OPTIONS -DCMAKE_SYSTEM_NAME=Windows "-DCMAKE_SYSTEM_PROCESSOR=${PROCESSOR}"
    -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded)
  set(FILENAME libyuv_internal.dll)
elseif(RID MATCHES "^osx-")
  if(NOT CMAKE_HOST_APPLE)
    message(FATAL_ERROR "macOS builds require an Apple SDK on a macOS host")
  endif()
  if(RID STREQUAL "osx-arm64")
    set(PROCESSOR arm64)
  else()
    set(PROCESSOR x86_64)
  endif()
  list(APPEND OPTIONS "-DCMAKE_OSX_ARCHITECTURES=${PROCESSOR}" -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0)
  list(APPEND OPTIONS -DCMAKE_SYSTEM_NAME=Darwin "-DCMAKE_SYSTEM_PROCESSOR=${PROCESSOR}")
  set(FILENAME libyuv_internal.dylib)
elseif(RID MATCHES "^android-")
  if(NOT ANDROID_NDK)
    set(ANDROID_NDK "$ENV{ANDROID_NDK_HOME}")
  endif()
  if(NOT EXISTS "${ANDROID_NDK}/build/cmake/android.toolchain.cmake")
    message(FATAL_ERROR "Set ANDROID_NDK to an NDK r28 or newer installation")
  endif()
  if(RID STREQUAL "android-arm64")
    set(ABI arm64-v8a)
  else()
    set(ABI x86_64)
  endif()
  list(APPEND OPTIONS "-DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK}/build/cmake/android.toolchain.cmake"
    "-DANDROID_ABI=${ABI}" -DANDROID_PLATFORM=android-23 -DANDROID_STL=c++_static)
  set(FILENAME libyuv_internal.so)
else()
  set(FILENAME libyuv_internal.so)
endif()

run("${CMAKE_COMMAND}" -S "${ROOT}/artifacts/libjpeg-turbo-3.2.0" -B "${WORK}/jpeg"
  ${OPTIONS} -DENABLE_SHARED=OFF -DENABLE_STATIC=ON -DWITH_TURBOJPEG=OFF
  -DWITH_TOOLS=OFF -DREQUIRE_SIMD=ON "-DCMAKE_INSTALL_PREFIX=${WORK}/jpeg-install")
run("${CMAKE_COMMAND}" --build "${WORK}/jpeg" --target jpeg-static --parallel)
run("${CMAKE_COMMAND}" --install "${WORK}/jpeg")
find_file(JPEG_ARCHIVE NAMES libjpeg.a jpeg-static.lib jpeg.lib
  PATHS "${WORK}/jpeg-install/lib" NO_DEFAULT_PATH)
if(NOT JPEG_ARCHIVE)
  message(FATAL_ERROR "The static JPEG library was not installed in ${WORK}/jpeg-install/lib")
endif()
run("${CMAKE_COMMAND}" -S "${ROOT}/native" -B "${WORK}/yuv" ${OPTIONS}
  "-DLIBYUV_SOURCE_DIR=${SOURCE}" "-DJPEG_LIBRARY=${JPEG_ARCHIVE}"
  "-DJPEG_INCLUDE_DIR=${WORK}/jpeg-install/include" "-DLIBYUV_RID=${RID}")
run("${CMAKE_COMMAND}" --build "${WORK}/yuv" --target yuv_shared libyuv_smoke --parallel)
set(DESTINATION "${ROOT}/LibYuvSharp/lib/runtimes/${RID}/native")
file(MAKE_DIRECTORY "${DESTINATION}")
file(COPY "${WORK}/yuv/libyuv/${FILENAME}" DESTINATION "${DESTINATION}")
file(COPY "${WORK}/yuv/libyuv/${FILENAME}" DESTINATION "${ROOT}/artifacts/runtimes/${RID}/native")
file(COPY "${SOURCE}/LICENSE" "${SOURCE}/PATENTS" "${SOURCE}/AUTHORS" DESTINATION "${ROOT}/native")
file(COPY "${ROOT}/artifacts/libjpeg-turbo-3.2.0/LICENSE.md"
  "${ROOT}/artifacts/libjpeg-turbo-3.2.0/README.ijg" DESTINATION "${ROOT}/native/libjpeg-turbo")
message(STATUS "Built ${DESTINATION}/${FILENAME}")
